#!/usr/bin/zsh

# github.com/pwnwriter/chadrice
# MIT license

# Sudo replacement for specific commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias "$command"="doas $command"
done
unset command

# Check if a program exists
_exists() {
	command -v "$1" >/dev/null 2>&1
}

# Aliases based on existence of specific commands
if _exists zoxide; then
	alias cd="z"
fi

if _exists bat; then
	alias cat="bat --theme=Catppuccin-macchiato"
fi

if _exists doas; then
	alias sudo="doas"
fi

# Always useful
alias \
	cp="cp -iv" \
	bc="bc -ql" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	wget="wget --no-hsts"

# Colorize commands where possible
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

# Additional aliases
alias \
	v="nvim" \
	gcl="git clone --depth=1 --filter=blob:none" \
	..="cd .." \
	sxiv="nsxiv" \
	...="cd ../ && cd ../" \
	cdtmp="cd \$(mktemp -d)"
