#!/bin/sh

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="doas $command"
done
unset command

# check if a command exists
_exists() {
  command -v $1 > /dev/null 2>&1
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	bc="bc -ql" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	wget="wget --no-hsts" \

if _exists zoxide; then
  alias cd="z"
fi

if _exists bat; then
  alias cat=" bat --theme=Catppuccin-macchiato"
fi

if _exists doas; then
  alias sudo="doas"
fi

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	sxiv="nsxiv" \
	ip="ip -color=auto" \
        cd="z" \
	..="cd .." \
	...="cd ../ && cd ../" \
	cdtmp="cd \$(mktemp -d)" \

alias \
	sudo="doas" \
	v="$EDITOR" \
	gcl="git clone --depth=1" \
