#!/bin/sh

# Copyright @pwnwriter/chadrice MIT License

launcher=wofi
menu=$(printf "reboot\nshutdown\n" "%s" | wofi --dmenu --width=300 --lines=4 --hide-scroll --prompt="What would you like?" --location=center 2>/dev/null)

pkill -9 $launcher

case "$menu" in
    "reboot")
    reboot
        ;;
    "shutdown")
    poweroff 
        ;;
    *)
        echo "Invalid selection"
        ;;
esac
