#!/bin/sh

# xinitrc runs automatically when you run startx.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
# sxhkd -c ~/.config/bspwm/sxhkdrc &
exec dbus-launch dwm
