#!/bin/bash

# Wallpaper changer

wall_dir="$HOME/.config/hypr/wallpapers"

selected_wall=$(find "$wall_dir/collections" -maxdepth 1 -type f -not -name 'current' -exec basename {} \; | wofi --dmenu --prompt="Select a wallpaper" --location=center --width=500 --height=400)

if [ -z "$selected_wall" ]; then
  exit 0
fi

if ! cp -f "$wall_dir/collections/$selected_wall" "$wall_dir/current"; then
  exit 1
fi

if pgrep -x "hyprpaper" > /dev/null; then
  pkill -9 hyprpaper
fi

# Start hyprpaper
setsid hyprpaper > /dev/null 2>&1 &
