#!/bin/sh

# Copyright @pwnwriter/chadrice MIT License

outdir="$HOME/screenshots"
mkdir -p "$outdir"
clipboard=wl-copy

generate_timestamp() {
  date +"%Y-%m-%d_%H-%M-%S"
}

no_selection() {
  filename="$outdir/screenshot_$(generate_timestamp).png"
  grim "$filename"
  $clipboard "$filename"
}

selection() {
  filename="$outdir/screenshot_$(generate_timestamp).png"
  grim -g "$(slurp)" "$filename"
  $clipboard "$filename"
}

if [ $# -eq 0 ]; then
  echo "Usage: $0 <no_selection|selection>"
  exit 1
fi

case "$1" in
  "no_selection" | "no-selection")
    no_selection
    ;;
  "selection")
    selection
    ;;
  *)
    echo "Invalid option. Usage: $0 <no_selection|selection>"
    exit 1
    ;;
esac

exit 0
