#!/bin/bash

# Wallpaper changer

wall_dir="$HOME/.config/hypr/wallpapers"
wall_file="$HOME/.config/hypr/hyprpaper.conf"

wall_name=$(ls "$wall_dir" --hide=current | wofi --dmenu --prompt="Select a wallpaper??" --location=center --width=500 --height=400)

if [ -z "$wall_name" ]; then
  exit 0
fi

command cp -f "$wall_name" "$wall_dir/current"

killall -9 hyprpaper
setsid hyprpaper > /dev/null &
