#!/usr/bin/zsh

# github.com/pwnwriter/dotfiles
# WTFPL license

# Sudo replacement for specific commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias "$command"="doas $command"
done
unset command

# Check if a program exists
_exists() {
	command -v "$1" >/dev/null 2>&1
}

# Aliases based on existence of specific commands
if _exists zoxide; then
	alias cd="z"
fi

if _exists bat; then
	alias cat="bat --theme=Catppuccin-macchiato"
fi

if _exists doas; then
	alias sudo="doas"
fi

if _exists eza; then
	alias \
                ls="eza --icons  -T -L 1 -x" \
	        ll="eza --icons  -T -L 2 -x" 
fi

# Always useful
alias \
	cp="cp -iv" \
	bc="bc -ql" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	wget="wget --no-hsts"

# Additional aliases
alias \
	v="nvim" \
	gcl="git clone --depth=1 --filter=blob:none" \
	sxiv="nsxiv" \
        cdtmp="cd \$(mktemp -d)" \
        ...="cd ../ && cd ../" \
        ..="cd .." \
