#!/bin/sh

if [ $# -lt 1 ] || [ ! -d "$1" ]; then
  printf "Usage:\n\t\e[1m%s\e[0m \e[4mDIRECTORY\e[0m\n" "$0"
  exit 1
fi

# See swww-img(1)
RESIZE_TYPE="fit"
export SWWW_TRANSITION_FPS="${SWWW_TRANSITION_FPS:-60}"
export SWWW_TRANSITION_STEP="${SWWW_TRANSITION_STEP:-2}"

# Pick one random image and set it as wallpaper
img=$(find "$1" -type f | shuf -n 1)

if [ -n "$img" ]; then
  swww img --resize="$RESIZE_TYPE" "$img"  --transition-type random
else
  echo "No images found in directory."
  exit 1
fi
