require('core.options')
require('pwn.plugins')
require('pwn.mappings')
require('config.bufferline')
require('config.nvim-tree')
require('config.lsp')
require('config.completion')
require('config.term')
require('config.theme')
require('config.autopair')

